title: E-Metatoul software & actions
markdown: kramdown

# for atom feed
author:
  name: e-metatoul
  #email: dev_sharad@outlook.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
    future: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
